# Generated by Django 3.2.11 on 2023-03-19 07:07

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='NG', max_length=2, verbose_name='country'),
        ),
    ]
